config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :orders

  namespace "guests" do
    resources :orders, only: [:index, :show]
  end

  get "/about", to: "landing#show"

  root "landing#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/order.rb
class EmailValidator < ActiveModel::EachValidator
  def validate_each(record, attribute, value)
    unless value =~ /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i
      record.errors.add attribute, (options[:message] || "is not an email")
    end
  end
end

class Order < ApplicationRecord
  enum spice_level: {
    mild: 10,
    hot: 20
  }

  PLATE_CENTS = 800
  SAUCE_CENTS = 50

  PLATES = (1..10)
  SAUCES = (0..10)

  validates :spice_level, inclusion: { in: spice_levels.keys, message: "%{value} is not a valid spice level" }
  validates_inclusion_of :plates, in: PLATES, message: "Must specify between 1 and 10 plates"
  validates_inclusion_of :extra_sauce, in: SAUCES, message: "Must specify between 0 and 10 servings extra sauce"
  validates :email, presence: true, email: true

  def price
    ((plates * PLATE_CENTS) + (extra_sauce * SAUCE_CENTS)) / 100.to_d
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, # :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :set_guest_code

  def set_guest_code
    session[:guest_code] = params[:guest_code] if params[:guest_code].present?

    session[:guest_code] ||= SecureRandom.uuid
  end

  def guest_code
    session[:guest_code]
  end

  helper_method :guest_code
end

app/controllers/guests/orders_controller.rb
class Guests::OrdersController < ApplicationController

  def index
    @orders = Order.where(guest_code: guest_code)
  end

  def show
  end
end

app/controllers/landing_controller.rb
class LandingController < ApplicationController
  def index
  end

  def show
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :authenticate_user!, except: [:new, :create, :show]
  before_action :set_order, only: %i[ show edit update destroy ]

  # GET /orders
  def index
    @orders = Order.all
  end

  # GET /orders/1
  def show
    redirect_to root_path unless current_user || @order.guest_code == session[:guest_code]
  end

  # GET /orders/new
  def new
    @order = Order.new
  end

  # GET /orders/1/edit
  def edit
  end

  # POST /orders
  def create
    @order = Order.new(order_params)
    @order.guest_code = guest_code

    if @order.save
      redirect_to @order, notice: "Order was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /orders/1
  def update
    if @order.update(order_params)
      redirect_to @order, notice: "Order was successfully updated."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  # DELETE /orders/1
  def destroy
    @order.destroy
    redirect_to orders_url, notice: "Order was successfully destroyed."
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_order
      @order = Order.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def order_params
      params.require(:order).permit(:plates, :spice_level, :extra_sauce, :note, :email)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/guests/orders/index.html.erb
<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Your Orders</h1>
    <%= link_to 'New order', new_order_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %>
  </div>

  <div id="orders" class="min-w-full">
    <%= render partial: "orders/order", collection: @orders, as: :order %>
  </div>
</div>

app/views/landing/index.html.erb
<ul>
  <li>See a menu</li>
  <li><%= link_to "Create an order", new_order_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %> </li>
  <li>Login w/ guest code</li>
  <li><%= link_to "See history of momos", "/about", class: "text-blue-500" %></li>
</ul>

app/views/landing/show.html.erb
<h1>Hello I am the about page</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MomoApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <header class="m-4">
      <%= link_to "Mount MoMo", "/" %>
      <%= link_to "Start an order", new_order_path, class: "rounded-lg py-2 px-3 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
      <%= link_to "See my orders", guests_orders_path, class: , class: "rounded-lg py-2 px-3 bg-slate-600 text-white inline-block font-medium cursor-pointer" %>
    </header>
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
    <main class="container mx-auto mt-28 px-5 flex">
      <%= yield %>
    </main>
  </body>
</html>

app/views/orders/_form.html.erb
<%= form_with(model: order, class: "contents") do |form| %>
  <% if order.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(order.errors.count, "error") %> prohibited this order from being saved:</h2>

      <ul>
        <% order.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div
    data-controller="price-preview"
    data-price-preview-plate-cents-value=<%= Order::PLATE_CENTS %>
    data-price-preview-sauce-cents-value=<%= Order::SAUCE_CENTS %>
    data-action="input->price-preview#updatePrice"
  >
    <div class="my-5">
      <%= form.label :plates %>
      <div>
        <%= form.select :plates, options_for_select(Order::PLATES), {}, data: { "price-preview-target": "plateInput" } %>
      </div>
    </div>

    <div class="my-5">
      <%= form.label :extra_sauce %>
      <div>
        <%= form.select :extra_sauce, options_for_select(Order::SAUCES), {}, { data: { "price-preview-target": "sauceInput" } } %>
      </div>
    </div>

    <div class="my-5">
      <%= form.label :spice_level %>
      <div>
        <%= form.select :spice_level, options_for_select(Order.spice_levels.map { |(k)| [k, k] }) %>
      </div>
    </div>

    <div>
      Estimated order price: <span data-price-preview-target="preview"></span>
    </div>
  </div>

  <div class="my-5">
    <%= form.label :note %>
    <%= form.text_area :note, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :email, "Email*" %>
    <%= form.text_field :email, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
    <div class="mt-4 text-sm text-gray-700">
      *order is sent to and coordinated via email
    </div>
    <div class="text-sm text-gray-700">
      *not used for marketing or any other purpose
    </div>
  </div>

  <div class="inline">
    <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/orders/_order.html.erb
<div id="<%= dom_id order %>">
  <div class="OrderGrid">
    <div>
      <p class="my-5 hidden">
        <strong class="block font-medium mb-1">Guest code:</strong>
        <%= order.guest_code %>
      </p>

      <p class="my-5">
        <strong class="block font-medium mb-1">Plates:</strong>
        <%= order.plates %>
      </p>

      <p class="my-5">
        <strong class="block font-medium mb-1">Spice level:</strong>
        <%= order.spice_level %>
      </p>

      <p class="my-5">
        <strong class="block font-medium mb-1">Extra sauce:</strong>
        <%= order.extra_sauce %>
      </p>

      <p class="my-5">
        <strong class="block font-medium mb-1">Note:</strong>
        <%= order.note %>
      </p>

      <p class="my-5">
        <strong class="block font-medium mb-1">Email:</strong>
        <%= order.email %>
      </p>
    </div>

    <div class="mt-5">
      <strong>Estimated price:</strong> <%= number_to_currency(order.price) %>
    </div>
  </div>

  <% if current_user %>
    <%= link_to "Show this order", order, class: "rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <%= link_to 'Edit this order', edit_order_path(order), class: "rounded-lg py-3 ml-2 px-5 bg-gray-100 inline-block font-medium" %>
    <hr class="mt-6">
  <% end %>
</div>

app/views/orders/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing order</h1>

  <%= render "form", order: @order %>

  <%= link_to "Show this order", @order, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Back to orders", orders_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/orders/index.html.erb
<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Orders</h1>
    <%= link_to 'New order', new_order_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %>
  </div>

  <div id="orders" class="min-w-full">
    <%= render @orders %>
  </div>
</div>

app/views/orders/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New order</h1>

  <%= render "form", order: @order %>

  <%= link_to 'Back to orders', root_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/orders/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <%= render @order %>

  <% if current_user %>
    <%= link_to 'Edit this order', edit_order_path(@order), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <div class="inline-block ml-2">
      <%= button_to 'Destroy this order', order_path(@order), method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
    </div>
    <%= link_to 'Back to orders', orders_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  </div>
  <% end %>
</div>